trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'jvaravindh/docker-demo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'